const sampleUserData = [
  {
    name: "John Doe",
    email: "john@example.com",
    password: "password123",
    role: "student",
    idCard: "ABCD12345",
    profileImage: "https://example.com/profile.jpg",
    idImage: "https://example.com/id.jpg",
    busNumber: "1",
    weight: 60,
    isAuthenticated: false,
    token: "token_string_1",
    penalty: 2,
  },
  {
    name: "Jane Smith",
    email: "jane@example.com",
    password: "securepass",
    role: "student",
    idCard: "EFGH6789",
    profileImage: "https://example.com/jane_profile.jpg",
    idImage: "https://example.com/jane_id.jpg",
    busNumber: "3",
    weight: 55,
    isAuthenticated: true,
    token: "token_string_2",
    penalty: 0,
  },
  {
    name: "Alice Johnson",
    email: "alice@example.com",
    password: "alicepass",
    role: "student",
    idCard: "IJKL9876",
    profileImage: "https://example.com/alice_profile.jpg",
    idImage: "https://example.com/alice_id.jpg",
    busNumber: "2",
    weight: 58,
    isAuthenticated: true,
    token: "token_string_3",
    penalty: 1,
  },
  {
    name: "Bob Roberts",
    email: "bob@example.com",
    password: "bobpass",
    role: "student",
    idCard: "MNOP54321",
    profileImage: "https://example.com/bob_profile.jpg",
    idImage: "https://example.com/bob_id.jpg",
    busNumber: "4",
    weight: 70,
    isAuthenticated: true,
    token: "token_string_4",
    penalty: 0,
  },
  {
    name: "Eva Green",
    email: "eva@example.com",
    password: "evapass",
    role: "student",
    idCard: "QRSTUV98765",
    profileImage: "https://example.com/eva_profile.jpg",
    idImage: "https://example.com/eva_id.jpg",
    busNumber: "7",
    weight: 62,
    isAuthenticated: true,
    token: "token_string_5",
    penalty: 0,
  },
  {
    name: "Chris Lee",
    email: "chris@example.com",
    password: "chrispass",
    role: "student",
    idCard: "WXYZ12345",
    profileImage: "https://example.com/chris_profile.jpg",
    idImage: "https://example.com/chris_id.jpg",
    busNumber: "6",
    weight: 65,
    isAuthenticated: true,
    token: "token_string_6",
    penalty: 3,
  },
  {
    name: "Sarah Johnson",
    email: "sarah@example.com",
    password: "sarahpass",
    role: "student",
    idCard: "ABCDE54321",
    profileImage: "https://example.com/sarah_profile.jpg",
    idImage: "https://example.com/sarah_id.jpg",
    busNumber: "5",
    weight: 56,
    isAuthenticated: true,
    token: "token_string_7",
    penalty: 0,
  },
  {
    name: "David Brown",
    email: "david@example.com",
    password: "davidpass",
    role: "student",
    idCard: "FGHIJ6789",
    profileImage: "https://example.com/david_profile.jpg",
    idImage: "https://example.com/david_id.jpg",
    busNumber: "9",
    weight: 68,
    isAuthenticated: true,
    token: "token_string_8",
    penalty: 1,
  },
  {
    name: "Linda Clark",
    email: "linda@example.com",
    password: "lindapass",
    role: "student",
    idCard: "KLMNO9876",
    profileImage: "https://example.com/linda_profile.jpg",
    idImage: "https://example.com/linda_id.jpg",
    busNumber: "10",
    weight: 61,
    isAuthenticated: true,
    token: "token_string_9",
    penalty: 0,
  },
  {
    name: "Alex Turner",
    email: "alex@example.com",
    password: "alexpass",
    role: "student",
    idCard: "PQRST54321",
    profileImage: "https://example.com/alex_profile.jpg",
    idImage: "https://example.com/alex_id.jpg",
    busNumber: "11",
    weight: 72,
    isAuthenticated: true,
    token: "token_string_10",
    penalty: 0,
  },
  {
    name: "Emily White",
    email: "emily@example.com",
    password: "emilypass",
    role: "student",
    idCard: "UVWXYZ6789",
    profileImage: "https://example.com/emily_profile.jpg",
    idImage: "https://example.com/emily_id.jpg",
    busNumber: "12",
    weight: 54,
    isAuthenticated: true,
    token: "token_string_11",
    penalty: 2,
  },
  {
    name: "Michael Davis",
    email: "michael@example.com",
    password: "michaelpass",
    role: "student",
    idCard: "ABCDE12345",
    profileImage: "https://example.com/michael_profile.jpg",
    idImage: "https://example.com/michael_id.jpg",
    busNumber: "13",
    weight: 66,
    isAuthenticated: true,
    token: "token_string_12",
    penalty: 0,
  },
  {
    name: "Sophia Lee",
    email: "sophia@example.com",
    password: "sophiapass",
    role: "student",
    idCard: "FGHIJ6789",
    profileImage: "https://example.com/sophia_profile.jpg",
    idImage: "https://example.com/sophia_id.jpg",
    busNumber: "14",
    weight: 59,
    isAuthenticated: true,
    token: "token_string_13",
    penalty: 1,
  },
  {
    name: "Robert Johnson",
    email: "robert@example.com",
    password: "robertpass",
    role: "student",
    idCard: "KLMNO9876",
    profileImage: "https://example.com/robert_profile.jpg",
    idImage: "https://example.com/robert_id.jpg",
    busNumber: "15",
    weight: 67,
    isAuthenticated: true,
    token: "token_string_14",
    penalty: 0,
  },
  {
    name: "Olivia Brown",
    email: "olivia@example.com",
    password: "oliviapass",
    role: "student",
    idCard: "PQRST54321",
    profileImage: "https://example.com/olivia_profile.jpg",
    idImage: "https://example.com/olivia_id.jpg",
    busNumber: "16",
    weight: 57,
    isAuthenticated: true,
    token: "token_string_15",
    penalty: 0,
  },
  {
    name: "William Turner",
    email: "william@example.com",
    password: "williampass",
    role: "student",
    idCard: "UVWXYZ6789",
    profileImage: "https://example.com/william_profile.jpg",
    idImage: "https://example.com/william_id.jpg",
    busNumber: "17",
    weight: 73,
    isAuthenticated: true,
    token: "token_string_16",
    penalty: 0,
  },
  {
    name: "Ava White",
    email: "ava@example.com",
    password: "avapass",
    role: "student",
    idCard: "ABCDE12345",
    profileImage: "https://example.com/ava_profile.jpg",
    idImage: "https://example.com/ava_id.jpg",
    busNumber: "18",
    weight: 63,
    isAuthenticated: true,
    token: "token_string_17",
    penalty: 3,
  },
  {
    name: "James Miller",
    email: "james@example.com",
    password: "jamespass",
    role: "student",
    idCard: "FGHIJ6789",
    profileImage: "https://example.com/james_profile.jpg",
    idImage: "https://example.com/james_id.jpg",
    busNumber: "19",
    weight: 58,
    isAuthenticated: true,
    token: "token_string_18",
    penalty: 0,
  },
  {
    name: "Grace Allen",
    email: "grace@example.com",
    password: "gracepass",
    role: "student",
    idCard: "KLMNO9876",
    profileImage: "https://example.com/grace_profile.jpg",
    idImage: "https://example.com/grace_id.jpg",
    busNumber: "20",
    weight: 69,
    isAuthenticated: true,
    token: "token_string_19",
    penalty: 1,
  },
  {
    name: "Daniel Smith",
    email: "daniel@example.com",
    password: "danielpass",
    role: "student",
    idCard: "PQRST54321",
    profileImage: "https://example.com/daniel_profile.jpg",
    idImage: "https://example.com/daniel_id.jpg",
    busNumber: "21",
    weight: 55,
    isAuthenticated: true,
    token: "token_string_20",
    penalty: 0,
  },
];

module.exports = sampleUserData;
